In [2]:
import pandas as pd

df = pd.read_parquet(
    "../data/processed/deliveries.parquet"
)

df.head()

,match_id,season,date,venue,city,team1,team2,winner,toss_winner,toss_decision,...,ball,batter,bowler,non_striker,batter_runs,extras,total_runs,extra_type,player_out,wicket_type
0,1469319,2024/25,2025-03-15,"Brabourne Stadium, Mumbai",Mumbai,Mumbai Indians,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,...,1,YH Bhatia,M Kapp,HK Matthews,0,0,0,None,None,None
1,1469319,2024/25,2025-03-15,"Brabourne Stadium, Mumbai",Mumbai,Mumbai Indians,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,...,2,YH Bhatia,M Kapp,HK Matthews,1,0,1,None,None,None
2,1469319,2024/25,2025-03-15,"Brabourne Stadium, Mumbai",Mumbai,Mumbai Indians,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,...,3,HK Matthews,M Kapp,YH Bhatia,0,0,0,None,None,None
3,1469319,2024/25,2025-03-15,"Brabourne Stadium, Mumbai",Mumbai,Mumbai Indians,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,...,4,HK Matthews,M Kapp,YH Bhatia,0,0,0,None,None,None
4,1469319,2024/25,2025-03-15,"Brabourne Stadium, Mumbai",Mumbai,Mumbai Indians,Delhi Capitals,Mumbai Indians,Delhi Capitals,field,...,5,HK Matthews,M Kapp,YH Bhatia,0,0,0,None,None,None

In [4]:
df.shape

(20656, 23)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20656 entries, 0 to 20655
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   match_id       20656 non-null  object
 1   season         20656 non-null  object
 2   date           20656 non-null  object
 3   venue          20656 non-null  object
 4   city           20656 non-null  object
 5   team1          20656 non-null  object
 6   team2          20656 non-null  object
 7   winner         20391 non-null  object
 8   toss_winner    20656 non-null  object
 9   toss_decision  20656 non-null  object
 10  innings        20656 non-null  int64
 11  batting_team   20656 non-null  object
 12  over           20656 non-null  int64
 13  ball           20656 non-null  int64
 14  batter         20656 non-null  object
 15  bowler         20656 non-null  object
 16  non_striker    20656 non-null  object
 17  batter_runs    20656 non-null  int64
 18  extras         20656 non-null  int64
 19  total_runs     20656 non-null  int64
 20  extra_type     914 non-null    object
 21  player_out     1079 non-null   object
 22  wicket_type    1079 non-null   object
dtypes: int64(6), object(17)
memory usage: 3.6+ MB

In [8]:
df.isnull().sum()

match_id             0
season               0
date                 0
venue                0
city                 0
team1                0
team2                0
winner             265
toss_winner          0
toss_decision        0
innings              0
batting_team         0
over                 0
ball                 0
batter               0
bowler               0
non_striker          0
batter_runs          0
extras               0
total_runs           0
extra_type       19742
player_out       19577
wicket_type      19577
dtype: int64

In [10]:
df["match_id"].nunique()

88

In [11]:
df["season"].value_counts()

season
2025/26    5250
2024/25    5230
2023/24    5177
2022/23    4999
Name: count, dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.duplicated(
    subset=["match_id", "innings", "over", "ball"]
).sum()

np.int64(0)

In [17]:
df[df["winner"].isna()][
    ["match_id", "season", "team1", "team2", "winner"]
].drop_duplicates()

      match_id   season                        team1        team2 winner
14503  1469306  2024/25  Royal Challengers Bengaluru  UP Warriorz   None

In [18]:
df[df["winner"].isna()]["match_id"].nunique()

1